### ISSUE TITLE
El contenedor 3D se va a full-screen al redimensionar ventana

### ISSUE THREAD

**Issue by virusu** [adrianalonsoba/THREEDC#3]
Si tengo una página con diferentes divs, siendo uno de ellos un div threedc, le pongo unas dimensiones iniciales. Por ejemplo:

   var SCREEN_WIDTH = 600;
   var SCREEN_HEIGHT = 800;

Pero al redimensionar la ventana de Chrome (al moverla a otra pantalla por ejemplo), el div se redimensiona sola poniéndose a ancho y alto de la pantalla completo (window.width y windows.height respectivamente), descuadrando y/o desplazando todos los demás divs. Creo que esto no debería ser así, sino que se deberían respetar de alguna forma las dimensiones iniciales.

**Comment by adrianalonsoba** [comment]
¿Estas usando la extensión de THREE.js THREEx.WindowResize.?

**Comment by virusu** [comment]
Ok. Era eso. Gracias ;)
